<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-SGPKRE7" failures="4" tests="9" name="Test" time="0.138" errors="0" timestamp="2024-12-18T08:08:20 GMT-08:00">
  <testcase classname="TestSuite.LoginTestCases" name="AboutUs" time="0.014"/>
  <testcase classname="TestSuite.LoginTestCases" name="Dashboard" time="0.002"/>
  <testcase classname="TestSuite.LoginTestCases" name="Logout" time="0.008">
    <failure type="java.lang.AssertionError" message="expected [7] but found [5]">
      <![CDATA[java.lang.AssertionError: expected [7] but found [5]
at TestSuite.LoginTestCases.Logout(LoginTestCases.java:10)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- Logout -->
  <testcase classname="TestSuite.HomeTestCases" name="BtnSignin" time="0.005"/>
  <testcase classname="TestSuite.HomeTestCases" name="TextPassword" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [4] but found [8]">
      <![CDATA[java.lang.AssertionError: expected [4] but found [8]
at TestSuite.HomeTestCases.TextPassword(HomeTestCases.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- TextPassword -->
  <testcase classname="TestSuite.HomeTestCases" name="TextUsername" time="0.004"/>
  <testcase classname="TestSuite.RegisterTestCases" name="txtEmail" time="0.004">
    <failure type="java.lang.AssertionError" message="expected [9] but found [8]">
      <![CDATA[java.lang.AssertionError: expected [9] but found [8]
at TestSuite.RegisterTestCases.txtEmail(RegisterTestCases.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- txtEmail -->
  <testcase classname="TestSuite.RegisterTestCases" name="txtFirst" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [2] but found [3]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [3]
at TestSuite.RegisterTestCases.txtFirst(RegisterTestCases.java:10)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- txtFirst -->
  <testcase classname="TestSuite.RegisterTestCases" name="txtLastName" time="0.003"/>
</testsuite> <!-- Test -->
